### ISSUE TITLE
Bundled thrust fails to compile under GCC 15 (std::allocator<>::reference removed)

### ISSUE THREAD

**Issue by henryiii** [GooFit/GooFit#387]
:robot: _AI text below_ :robot:

## Summary

The bundled `extern/thrust` submodule does not compile with **GCC 15** (e.g. the `rootproject/root:6.38.00-ubuntu25.10` image, or any ubuntu 25.10-era toolchain). It builds fine on GCC 13 (ubuntu24.04).

## Error

```
extern/thrust/thrust/detail/contiguous_storage.h:49:56: error: no type named 'reference' in 'class std::allocator<double>'
extern/thrust/thrust/detail/contiguous_storage.h:50:56: error: no type named 'const_reference' in 'class std::allocator<double>'
```

## Cause

`std::allocator<T>::reference` / `const_reference` were deprecated in C++17 and **removed in C++20**; libstdc++ dropped them in the GCC 15 release. The bundled thrust copy still references those removed allocator member typedefs, so it no longer compiles against GCC 15's libstdc++. This is independent of the GooFit C++ standard setting.

## Impact / current workaround

- Not hit today because CI and most dev toolchains are still on GCC <= 13/14.
- The new OMP / Python CI job (added in #386) deliberately pins `rootproject/root:6.34.00-ubuntu24.04` (GCC 13) to avoid this; a note in `.github/workflows/ci.yml` explains why.

## Suggested fix

Bump the bundled thrust submodule to a version that uses `allocator_traits` instead of the removed allocator member typedefs (modern NVIDIA CCCL/thrust). Mind the existing dual-Thrust constraint: CUDA 12/13 ship their own thrust (`GOOFIT_FORCE_LOCAL_THRUST=OFF`), so any bump must stay compatible with both the local-thrust and system-thrust paths. Once resolved, the Python CI job can move to a newer ROOT/Ubuntu image.
